services:
  tgisper:
    build:
      context: .
      dockerfile: Dockerfile
    user: appuser
    environment:
      - ASR_MODEL=small
      - OMP_NUM_THREADS=2
    volumes:
      - cache:/home/appuser/.cache
    restart: always

volumes:
  cache:
